version: '3.8'

services:
  redis:
    image: redis:latest
    container_name: go_bot_redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    command: ["credis-server", "--appendonly", "yes"]

volumes:
  redis_data:
    driver: local